AspNetMvcCoreExamples.Web/Controllers/AjaxController.cs
namespace AspNetMvcCoreExamples.Web.Controllers
{
    using System.Linq;
    using AspNetMvcCoreExamples.Web.Data;
    using AspNetMvcCoreExamples.Web.Models;
    using Microsoft.AspNetCore.Mvc;

    public class AjaxController : Controller
    {
        private readonly ApplicationDbContext context;

        public AjaxController(ApplicationDbContext context)
        {
            this.context = context;
        }

        // GET: Ajax
        public IActionResult Index()
        {
            var viewModel = new SearchViewModel();
            return this.View(viewModel);
        }

        public PartialViewResult _AjaxPartial(SearchViewModel viewModel)
        {
            var titles = this.context.Movies
                .Where(m => m.Title.Contains(viewModel.Title))
                .Select(m => m.Title);

            return this.PartialView(model: string.Join(", ", titles));
        }
    }
}

AspNetMvcCoreExamples.Web/Views/Ajax/Index.cshtml
@model AspNetMvcCoreExamples.Web.Models.SearchViewModel

@{
    ViewBag.Title = "Index";
}

<h2>Get movies by title</h2>

@*TODO
@using (Ajax.BeginForm("_AjaxPartial", "Ajax", new AjaxOptions
{
    InsertionMode = InsertionMode.Replace, 
    UpdateTargetId = "searchResult",
    LoadingElementId = "loader" 
}))
{
    @Html.EditorFor(x => x.Title)
    <input type="submit" value="Search" />
}

<div id="loader"  style="display:none">
    Loading...
</div>

@Html.Partial("_AjaxPartial", string.Empty)

@section scripts{
    <script src="~/Scripts/jquery.unobtrusive-ajax.js" type="text/javascript"></script>
}*@

AspNetMvcCoreExamples.Web/Views/Ajax/_AjaxPartial.cshtml
@model string

<div id="searchResult">
    @Model
</div>